name: Jen Cotten Art
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5dbe3'
    - '#101413'
    - '#453922'
    - '#515c56'
    - '#93aba6'
  brandStrength: 0.625
  lightness: 0.060623231343925
  saturation: 1
  rhythmicContrast: 0.6295077595859766
purpose: []
